theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jemoji

relative_links:
  enabled: true
  collections: true

title: "airplanes.live App"
description: "An Android app for airplanes.live"
author: "by Matthias Urhahn"

include:
  - PRIVACY_POLICY.md
exclude:
  - app
  - buildSrc
  - gradle/wrapper
